# Generated by Django 6.0.1 on 2026-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('fill_level', models.IntegerField()),
                ('last_collected', models.DateTimeField()),
                ('overflow_risk', models.BooleanField(default=False)),
            ],
        ),
    ]
