# Generated by Django 6.0.1 on 2026-02-04 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('reported_by', models.CharField(default='Anonymous', max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gov_notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='garbagebin',
            name='last_collected',
        ),
        migrations.AddField(
            model_name='garbagebin',
            name='last_emptied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='garbagebin',
            name='status',
            field=models.CharField(default='safe', max_length=20),
        ),
        migrations.AlterField(
            model_name='garbagebin',
            name='fill_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='garbagebin',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
