# Generated by Django 6.0.1 on 2026-02-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_complaint_remove_garbagebin_last_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('overflow', 'Bin Overflow'), ('smell', 'Bad Odor'), ('damaged', 'Damaged Bin'), ('not_emptied', 'Not Emptied Regularly'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
